# .github/workflows/reviewdog_black.yml
name: reviewdog
on: [pull_request]
jobs:
  black:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install black
      - name: do black
        run: black .
      - name: get reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
          ./bin/reviewdog -version
      # by https://github.com/reviewdog/action-suggester/tree/master
      - name: get diff
        run: |
          TMPFILE=$(mktemp)
          git diff > "${TMPFILE}"
          export REVIEWDOG_GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./bin/reviewdog \
          -f diff \
          -f.diff.strip=1 \
          -reporter="github-pr-review" \
          -filter-mode="diff_context" \
          -fail-on-error="true" \
          -level="warning"  <"${TMPFILE}"
